### ISSUE TITLE
error after npm start

### ISSUE THREAD

**Issue by harshiths037** [Tyriar/vscode-theme-generator-quick-start#2]
```
> tsc index.ts

node_modules/@types/node/index.d.ts:20:1 - error TS1084: Invalid 'reference' directive syntax.

20 /// <reference lib="es2016" />
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! generated-theme@0.0.1 prestart: `tsc index.ts`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the generated-theme@0.0.1 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:`
```

**Comment by Tyriar** [comment]
Looks like this is related to a lack of a package/yarn lock file. `npm i -D @types/node@7` will probably work (maybe also downleveling typescript).

**Comment by Juka99** [comment]
I am getting this exact same problem, `npm i -D @types/node@7` also didn't work ... Is there any fix for this yet ? I would really like to try your repository.

**Comment by lewislbr** [comment]
That seems to happen because of outdated dependencies. I've been able to fix it running `npx npm-check-updates -u` and then `npm i`.

**Comment by jfcode27** [comment]
> That seems to happen because of outdated dependencies. I've been able to fix it running `npx npm-check-updates -u` and then `npm i`.

This worked, ty.

**Comment by oxamila** [comment]
> npx npm-check-updates -u

its working. thank you
