### ISSUE TITLE
not run

### ISSUE THREAD

**Issue by amirmansoori** [Tyriar/vscode-theme-generator-quick-start#3]
node_modules/@types/node/index.d.ts:20:1 - error TS1084: Invalid 'reference' 
directive syntax.

20 /// <reference lib="es2016" />
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by Tyriar** [comment]
duplicate of https://github.com/Tyriar/vscode-theme-generator-quick-start/issues/2
